id: P006646
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:12:37.883654
source_metadata:
  id: bdr:W1CZ1163
  title: གཤིན་རྗེ་གཤེད་ཀྱི་རྫོགས་རིམ་།
  author: ''
  volumes:
    32dd78d4ecdb47938af6ccfc50707e7a:
      image_group_id: I1CZ1590
      title: ''
      volume_number: 1
      total_pages: 22
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
